#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap -layout es &
nitrogen --restore &
picom &
xrdb ~/.Xresources &
nvidia-settings -l &
polybar right&
polybar left&
light-locker&
imwheel -b 45&

bspc monitor DP-4 -d I II III IV V
bspc monitor DP-2 -d VI VIII IX X

bspc config border_width 2
bspc config window_gap 50
bspc config split_ratio 0.52

bspc config active_border_color \#9423f8
bspc config focused_border_color \#B38AB0
bspc config normal_border_color \#addbed

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
